import { StyleSheet } from "react-native";

export const colors = {
  warning: "#f0ad4e",
  danger: "#d9534f",
  success: "#5cb85c",
  primary: "#337ab7",
  gray: "#6c757d",
  black: "#000",
  white: "#fff",
  purple: "#6f42c1",
};

export const global_styles = StyleSheet.create({
  title: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    margin: 10,
  },
  subTitle: {
    fontSize: 20,
    fontWeight: "600",
    textAlign: "center",
    marginVertical: 10,
  },
  subTitleDivider: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginVertical: 10,
    width: "100%",
    borderBottomWidth: 2,
    borderBottomColor: colors.danger,
    paddingVertical: 5,
    borderTopColor: colors.danger,
    borderTopWidth: 2,
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: "bold",
  },
  text_btn: {
    color: "white",
    textAlign: "center",
    fontSize: 16,
    width: "100%",
    height: "100%",
  },
  picker: {
    borderBottomColor: colors.primary,
    borderBottomWidth: 1,
    marginBottom: 10,
    fontSize: 16,
  },
  mv10: {
    marginVertical: 10,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cancelled_title: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.danger,
    marginBottom: 8,
  },
  pending_title: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.warning,
    marginBottom: 8,
  },
  confirmed_title: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.success,
    marginBottom: 8,
  },
  delivered_title: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.black,
    marginBottom: 8,
  },
  input: {
    borderBottomColor: colors.primary,
    borderBottomWidth: 1,
    fontSize: 16,
    marginBottom: 10,
    paddingVertical: 5,
    paddingHorizontal: 10,
    width: "90%",
    color: colors.black,
  },
  row_between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 15,
    borderRadius: 5,
    borderBottomColor: colors.gray,
    borderBottomWidth: 1,
  },
});
